apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - bitnami-oci-secret.yaml
  - rabbitmq.yaml
  - redis.yaml
  - rabbitmq-creds.yaml
  - redis-creds.yaml
#preprod
  - redis-preprod.yaml
  - redis-creds-preprod.yaml
