apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: rabbitmq-creds
  namespace: rabbitmq
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: repo-creds-secret-store
    kind: ClusterSecretStore
  target:
    name: rabbitmq
    template:
      data:
        rabbitmq-password: "{{ .rabbitmqPassword }}"
        rabbitmq-erlang-cookie: "{{ .rabbitmqErlangCookie }}"
  data:
    - secretKey: "rabbitmqPassword"
      remoteRef:
        key: "REPLACE_ME"
    - secretKey: "rabbitmqErlangCookie"
      remoteRef:
        key: "REPLACE_ME"
