apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbitmq
  namespace: argocd
spec:
  destination:
    namespace: rabbitmq
    server: "https://kubernetes.default.svc"
  source:
    repoURL: "registry-1.docker.io/bitnamicharts"
    chart: "rabbitmq"
    path: 'rabbitmq'
    targetRevision: "14.4.0"
    helm:
      valuesObject:
        persistence:
          enabled: true
          size: 4Gi
        ingress:
          enabled: true
          hostname: "PATCH_ME"
          ingressClassName: "nginx"
          annotations:
            cert-manager.io/cluster-issuer: "letsencrypt-prod"
          tls: true
          existingSecret: "rabbitmq-tls-secret"
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
