apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: redis-creds
  namespace: redis
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: repo-creds-secret-store
    kind: ClusterSecretStore
  target:
    name: redis-password
    template:
      data:
        redis-password: "{{ .redisPassword }}"
  data:
    - secretKey: "redisPassword"
      remoteRef:
        key: "REPLACE_ME"
