apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: github-credentials
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repo-creds
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: repo-creds-secret-store
    kind: ClusterSecretStore
  target:
    name: github-credentials
    template:
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repository
      data:
        username: "kloia"
        url: https://github.com/kloia/platform-gitops.git
        password: "{{ .githubToken }}"
        type: git
  data:
    - secretKey: "REPLACE_ME"
      remoteRef:
        key: "REPLACE_ME"
