apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: repo-creds-secret-store
spec:
  provider:
    gcpsm:
      projectID: kloia
      auth:
        workloadIdentity:
          clusterLocation: location
          # name of the GKE cluster
          clusterName: kloia-k8s
          # projectID of the cluster (if omitted defaults to spec.provider.gcpsm.projectID)
          clusterProjectID: kloia
          # reference the sa from above
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets
