apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbitmq
  namespace: argocd
spec:
  source:
    helm:
      valuesObject:
        ingress:
          hostname: "rabbitmq.kloia.com"
        auth:
          existingPasswordSecret: "rabbitmq"
          existingErlangSecret: "rabbitmq"
        resources:
          limits:
            memory: 1Gi
          requests:
            cpu: 250m
            memory: 512Mi