apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis
  namespace: argocd
spec:
  source:
    helm:
      valuesObject:
        auth:
          existingSecret: redis-password
          existingSecretPasswordKey: redis-password
          usePasswordFiles: true
        metrics:
          enabled: true
        master:
          resources:
            limits:
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 512Mi