apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: redis-creds
  namespace: redis
spec:
  data:
    - secretKey: "redisPassword"
      remoteRef:
        key: "kloia_redis_prod_password"
