apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  data:
    - secretKey: apiToken
      remoteRef:
        key: cloudflareApiToken