apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: repo-creds-secret-store
    kind: ClusterSecretStore
  target:
    name: cloudflare-api-token-secret
    template:
      data:
        api-token: "{{ .apiToken }}"
  data:
    - secretKey: "apiToken"
      remoteRef:
        key: "REPLACE_ME"
