apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: github-credentials
  namespace: argocd
spec:
  data:
    - secretKey: githubToken
      remoteRef:
        key: githubToken
