apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/

patches:
  - path: patches/external-secrets/role-arn.yaml
  - path: patches/monitoring/cluster-info.yaml
  - path: patches/logging/loki-storage.yaml
  - path: patches/ingress-nginx/cluster-info.yaml
