apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
spec:
  destination:
    namespace: external-secrets
    server: "https://kubernetes.default.svc"
  source:
    repoURL: "https://charts.external-secrets.io"
    chart: "external-secrets"
    targetRevision: "0.9.18"
    helm:
      valuesObject:
        serviceAccount:
          name: "external-secrets"
          annotations:
            iam.gke.io/gcp-service-account: example-team-a@my-project.iam.gserviceaccount.com
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
