apiVersion: v1
kind: Secret
metadata:
  labels:
    argocd.argoproj.io/secret-type: repository
  name: ghcr-io-helm-oci
  namespace: argocd
stringData:
  url: ghcr.io/kube-logging/helm-charts
  name: helm-charts
  type: helm
  enableOCI: "true"