apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: logging-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  destination:
    namespace: logging
    server: "https://kubernetes.default.svc"
  source:
    repoURL: ghcr.io/kube-logging/helm-charts
    chart: logging-operator
    targetRevision: "4.3.0"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
